version: '3.7'

services:
  iseeapi-dev:
    restart: always
    container_name: iseeapidev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'

  iseedatabase-dev:
    container_name: iseedatabasedev
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - isee-volume-database-dev:/data/db
    restart: unless-stopped

volumes:
  isee-volume-database-dev: {}
